language: python
sudo: false
python:
  - "2.7"
  - pypy
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install --src . -r requirements.txt"
# command to run tests, e.g. python setup.py test
script:
  - "nosetests --with-cov --cov-report term-missing"
  - "autopep8 -i -r -a -a . && test -z \"$(git status -s)\""
  - "autoflake -r -i --remove-all-unused-imports --remove-unused-variables . && test -z \"$(git status -s)\""
after_success:
  - coveralls
notifications:
  irc:
    channels:
      - "irc.oftc.net#mitmproxy"
    on_success: change
    on_failure: always
cache:
  directories:
  - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
  - /home/travis/virtualenv/python2.7.9/bin
  - /home/travis/virtualenv/pypy-2.5.0/site-packages
  - /home/travis/virtualenv/pypy-2.5.0/bin
